Appointment/force-app/main/default/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Reason</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Appointment/force-app/main/default/main/default/objects/Appointment__c/fields/Appointment_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date_and_Time__c</fullName>
    <label>Date and Time</label>
    <type>DateTime</type>
</CustomField>

Appointment/force-app/main/default/main/default/objects/Appointment__c/fields/Appointment_Location__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Location__c</fullName>
    <label>Location</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Appointment/force-app/main/default/main/default/objects/Appointment__c/fields/Appointment_Reason__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Reason__c</fullName>
    <label>Appointment Reason</label>
    <type>TextArea</type>
</CustomField>

Appointment/force-app/main/default/main/default/objects/Appointment__c/fields/Banker__c.field-meta.xml
<CustomField>
    <fullName>Banker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banker</label>
    <referenceTo>Banker__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

Appointment/force-app/main/default/main/default/objects/Appointment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Appointment/force-app/main/default/main/default/objects/Banker__c/Banker__c.object-meta.xml
<CustomObject>
    <label>Banker</label>
    <nameField>
        <label>Banker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bankers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Appointment/force-app/main/default/main/default/objects/Banker__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipLabel>Bankers</relationshipLabel>
    <relationshipName>Bankers</relationshipName>
    <type>Lookup</type>
</CustomField>

Appointment/force-app/main/default/classes/BankerController.cls
public with sharing class BankerController {
    @AuraEnabled(cacheable=true)
    public static List<Appointment__c> getAppointmentsForBanker() {
        Id bankerId = 'a08dM00000DFfZdQAL';
        return [
            SELECT Id, Name,  Contact__c, Contact__r.Name, Appointment_Reason__c, Appointment_Date_and_Time__c, Duration__c, Appointment_Location__c, Pincode__c, Banker__c
            FROM Appointment__c
            WHERE Banker__c = :bankerId
            //AND Appointment_Date_and_Time__c >= TODAY
            ORDER BY Appointment_Date_and_Time__c ASC
        ];
    }
    
    @AuraEnabled
    public static Appointment__c createAppointment(Appointment__c newAppt) {
        insert newAppt;
        return newAppt;
    }
}